### ISSUE TITLE
Rejections to OB10 suppliers

### ISSUE THREAD

**Issue by Astrakp1** [Laykou/Maple#120]
if invoice=OB10 and Rejection back to vendor, send separate email

**Comment by Laykou** [comment]
Toto uz vieme spravit workflowom.

**Comment by Astrakp1** [comment]
Ano, spravil som zatial toto: http://maple.jci.com/workflow_rules/view/35
(vsetky pending back to vendor sa automaticky zmenia na returned to vendor).

Potom som pripravil rejection template: http://maple.jci.com/email_templates/view/34

Chyba mi ale jedna vec, aby pre vsetky faktury, ktore su OB10, sa pre action "Back to vendor" zobrazilo este povinne pole "receiver" (pre ostatne barcody sa toto pole ani nezobrazi). Co myslis?

Dik

**Comment by Astrakp1** [comment]
duplicate to #148
