### ISSUE TITLE
Scanning: Special reports

### ISSUE THREAD

**Issue by Laykou** [Laykou/Maple#136]
This relates to the #119 but I'm creating a new issue as we can discuss it separately. I was told by Dominika (28.11.2014) that they would like to have these kind of reports:

1. Prepared/scanned [October/November]
  - entity
  - barcode
  - created on
  - scanned on 
  - created by
  - scanned by
  - batch flag (Quick)
  - urgent

2. Pre-rejection/ rejection (R0, R1, R2, R3, R4, R5, R6) [November]
  - entity
  - barcode
  - created on 
  - scanned on 
  - last reason (R0, R1, R2, R3, R4, R5, R6)
  - pending back to vendor on (if it is rejection)
  - change details on (if it is marked as prerejection)
  - change details by (if it is marked as prerejection)
  - returned to vendor on
  - returned to vendor by

@Astrakp1 Is it necessary? Currently it is not possible to get these kind of data directly from Maple by *One-click* action. Could you please get more information about this?

**Comment by Astrakp1** [comment]
uz netreba:)
