### ISSUE TITLE
Due Dilligence tool

### ISSUE THREAD

**Issue by Astrakp1** [Laykou/Maple#203]
# Due Dilligence tool
Checking blocked invoices and comparing to the iScala.
There are three statuses: **New**, **Reviewed**, **Confirmed**.
There are three groups with various access permissions: **Uploaders** (reporting), **Reviewers** (helpdesk), **Confirmers** (payment).

## Database fields
Table will be named `due_dilligence_invoices`. All the fields are **text only**.
- supplier type *(excel column no. 55)*
- invoice due date *(excel column no. 31)*
- entity (org) *(excel column no. 27)*
- barcode *(excel column no. 8 )*
- inv.number *(excel column no. 16)*
- supplier !escape *(excel column no. 12)*
- invoice date *(excel column no. 30)*
- amount *(excel column no. 34)*
- currency *(excel column no. 35)*
- PO *(excel column no. 26)*
- ref.number *(excel column no. 9 )*
- company code *(excel column no. 5)* - used for updating column 27
 - if the entity (column 27) does not exists it is loaded from database based on company code in table entities. Use provided iScala file to update the entities list with their company codes.
- invoice block/ payment block *(excel column no. 17)*
- status
- review_comment
- confirm_comment

## Upload
Upload only those rows, where supplier type is one of these:
- BUSC
- CHAR
- CUST
- FF
- GVBC
- GVER
- SALC
- SHIP
- SPON

Unique row (invoice) is identified by the combination of **entity + supplier + invoice number**.

### How does the upload works?
For each row in the Excel:
- If the row does not exists, it is inserted with the `status = New`
- else if the row exists
  - data are updated
  - if the `invoice_block` has been changed set the `invoice_block_changed` to `1`.
  - else if the `invoice_block` has not been changed, no action

## Groups and actions
- Uploaders
  - can upload the Excel file
- Reviewers
  - can operate only **New** invoices
  - can set the comment and mark the invoice as **Reviewed**
- Confirmers
  - can operate only **Reviewed** invoices
  - can set *optional* comment and mark the invoice as **Confirmed**

The `barcodes` table in the Maple is connected with the rows in the due dilligence by the `barcode` text field. In the due dilligence there will be invoice image visible, in the Barcodes there will be the status of the due dilligence invoice visible.

**Comment by Laykou** [comment]
Hotovo.

**Comment by Astrakp1** [comment]
Laci, skvele, hlavicky vyzeraju super, ale nevidno ani jednu DD fakturu, skusal som si aj menit role, cistit filter, ale ani jednu fakturu nevidim
