### ISSUE TITLE
/barcodes/ download to excel

### ISSUE THREAD

**Issue by Astrakp1** [Laykou/Maple#230]
- [x] add date of last reminder/escalation into download to excel

**Comment by Laykou** [comment]
Hotovo.

**Comment by Astrakp1** [comment]
otestoval som, vidim hlavicku "last remindered on", ale napr. pre barcode 025500009874 sa nezobrazuje last reminder, hoci by tam mal byt 24.4.2015. Dik za check

**Comment by Laykou** [comment]
Zabudol som spustit query, ktora mala upravit vsetky existujuce barcody. Uz by to malo byt, mozes skusit znovu.

**Comment by Astrakp1** [comment]
diky
